version: '3'
services:
  web2:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql2
    volumes:
      - .:/var/www

  mysql2:
    image: mysql:5.7.17
    container_name: mysql2
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root