version: '3'
services:
  web2:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    #entrypoint: ./docker/docker-entrypoint.sh
    #command: bash -c "composer update && composer development-enable && php public/index.php orm:schema-tool:update --dump-sql --force"
    container_name: web2
    ports:
      - "84:80"
      - "444:443"
    links:
      - mysql2
      - redis2
    volumes:
      - .:/var/www
    tty: true

  mysql2:
    image: mysql:5.7.17
    container_name: mysql2
    ports:
      - "3302:3306"
    volumes:
      - mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dealerapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  redis2:
    image: redis:3.2.7
    container_name: redis2
    ports:
      - "6379:6379"

  blackfire2:
    image: blackfire/blackfire
    container_name: blackfire2
    environment:
      # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
      - BLACKFIRE_SERVER_ID=57961115-e0e3-4e85-acf0-683213488374
      - BLACKFIRE_SERVER_TOKEN=20d05fdb176146c69195247730a281dd82fda6026c93c21d779b5c35d720e2d9
      # You can also use global environment credentials :
      # BLACKFIRE_SERVER_ID: SERVER-ID
      # BLACKFIRE_SERVER_TOKEN: SERVER-TOKEN

volumes:
  mysql2:
    driver: local