version: '3'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    #entrypoint: ./docker/docker-entrypoint.sh
    #command: bash -c "composer update && composer development-enable && php public/index.php orm:schema-tool:update --dump-sql --force && /usr/bin/apachectl -D FOREGROUND"
    container_name: web2
    networks:
      - local
    ports:
      - "82:80"
      - "442:443"
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www
    tty: true

  mysql:
    image: mysql:5.7.17
    container_name: mysql2
    networks:
      - local
    ports:
      - "3302:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dealerapp
      MYSQL_USER: ismail
      MYSQL_PASSWORD: ismail

  redis:
    image: redis:3.2.7
    container_name: redis2
    ports:
      - "6379:6379"

volumes:
  mysql:
    driver: local

networks:
  local:
    driver: bridge