version: '3'
services:
  web2:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    container_name: web2
    ports:
      - "84:80"
      - "444:443"
    links:
      - mysql2
    volumes:
      - .:/var/www
    tty: true

  mysql2:
    image: mysql:5.7.17
    container_name: mysql2
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dealerapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root