<?php
/**
 * Created by PhpStorm.
 * User: ismail
 * Date: 2-2-17
 * Time: 13:54
 */

$title = 'Dealers';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('dealer', ['action' => 'add']) ?>">Add new dealer</a>
</p>
<p>
    <a href="<?= $this->url('dealer', ['action' => 'import']) ?>">Import dealers</a>
</p>
<p>
    <a href="<?= $this->url('dealer', ['action' => 'export']) ?>">Export dealers</a>
</p>
<div class="g-savetodrive"
     data-src="<?= $this->url('dealer', ['action' => 'export']) ?>"
     data-filename="My Statement.xls"
     data-sitename="My Company Name">
</div>

<script type="text/javascript">
    window.___gcfg = {
        lang: 'nl-NL'
    };
</script>
<script src = 'https://apis.google.com/js/platform.js' async defer></script>
<table class="table">
    <tr>
        <th>Name</th>
        <th>City</th>
        <th>Meta1</th>
        <th>Meta2</th>
        <th>&nbsp;</th>
    </tr>
    <?php /** @var \Application\Entity\Dealer $dealer */
    foreach ($dealers as $dealer) : ?>
        <tr>
            <td><?= $this->escapeHtml($dealer->getName()) ?></td>
            <td><?= $this->escapeHtml($dealer->getCity()) ?></td>
            <td><?= $this->escapeHtml($dealer->getMeta1()) ?></td>
            <td><?= $this->escapeHtml($dealer->getMeta2()) ?></td>
            <td>
                <a href="<?= $this->url('dealer', ['action' => 'edit', 'id' => $dealer->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('dealer', ['action' => 'delete', 'id' => $dealer->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>